# Generated by Django 6.0.2 on 2026-02-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('area_sqft', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('metro_distance', models.FloatField()),
                ('crime_rate', models.FloatField()),
                ('pollution', models.FloatField()),
                ('infrastructure', models.FloatField()),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('investment_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
