# Generated by Django 6.0.2 on 2026-04-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plot_created_by_plot_image_plot_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
