# Generated by Django 6.0.2 on 2026-04-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_plot_latitude_alter_plot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='infrastructure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
