# Generated by Django 6.0.2 on 2026-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='crime_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='metro_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='pollution',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
